# Generated by Django 4.0.6 on 2022-07-14 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('advertising_id', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=255)),
                ('device_model', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_os', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('push_token', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
