# Generated by Django 4.0.6 on 2022-07-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_Anuradha', '0002_alter_installation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='advertising_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
